Feature update synchronize gitaction (#60)
* update sync

* update syn

* update syn

* update syn

* update sync

* update

* update

* test dbt test

* undo

* undo

* change the order of test and seed

* correction apres le review

diff --git a/.github/workflows/synchronize_db.yaml b/.github/workflows/synchronize_db.yaml
--- a/.github/workflows/synchronize_db.yaml
+++ b/.github/workflows/synchronize_db.yaml
@@ -42,6 +42,16 @@ jobs:
       run: |
         uv run pipelines/run.py run build_database --refresh-type all --check-update
 
+    - name: Install dbt dependencies
+      run: |
+        cd dbt_
+        uv run dbt deps || { echo "dbt deps failed"; exit 1; }
+    
+    - name: Create tables/views in dbt
+      run: |
+        cd dbt_
+        uv run dbt build || { echo "dbt build failed"; exit 1; }
+
     - name: Upload production database to Storage
       run: |
         uv run pipelines/run.py run upload_database
