add dbt docs generate to dbt test (#92)

diff --git a/.github/workflows/test_dbt.yaml b/.github/workflows/test_dbt.yaml
--- a/.github/workflows/test_dbt.yaml
+++ b/.github/workflows/test_dbt.yaml
@@ -35,3 +35,8 @@ jobs:
       run: |
         cd dbt_
         uv run dbt build || { echo "dbt build failed"; exit 1; }
+        
+    - name: Run dbt docs generate
+      run: |
+        cd dbt_
+        uv run dbt docs generate || { echo "dbt docs generate failed"; exit 1; }
